config/routes.rb
Rails.application.routes.draw do
  resources :notice_requirements, only: %i[index show edit destroy create new]

  root 'notice_requirements#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice_requirement.rb
class NoticeRequirement < ApplicationRecord
  module Topics
    ABOUT = "About The Notices"
    INCLUDE_GENERAL = "What must be included? - General"
    INCLUDE_OPTOUT = "What must be included? - Opt-out"
    INCLUDE_PRIVACY = "What must be included? - Privacy Policy"
    INCLUDE_FINANCIAL = "What must be included? - Financial Incentives"
    OFFLINE_SPECIFIC = "Offline Specific"
    EXEMPTIONS = "Exemptions"
    ADDITIONAL_INFO = "Additional Information About Notices"

    def self.all
      [ABOUT, INCLUDE_GENERAL, INCLUDE_OPTOUT, INCLUDE_PRIVACY, INCLUDE_FINANCIAL, OFFLINE_SPECIFIC, EXEMPTIONS, ADDITIONAL_INFO]
    end
  end
  validates :topic, inclusion: { in: Topics.all }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notice_requirements_controller.rb
class NoticeRequirementsController < ApplicationController
  before_action :set_notice_requirement, only: [:show, :edit, :update, :destroy]

  # GET /notice_requirements
  # GET /notice_requirements.json
  def index
    topic = params[:topic] || ''
    act_citation = params[:act_citation] || ''
    reg_citation = params[:reg_citation] || ''
    text_search = params[:text_search] || ''
    @notice_requirements = NoticeRequirement.where('topic LIKE ?', "%#{topic}%")
                                            .where('act_cites LIKE ?', "%#{act_citation}%")
                                            .where('regulation_cites LIKE ?', "%#{reg_citation}%")
                                            .where('requirement LIKE ?', "%#{text_search}%")
    @act_citations = act_citations
    @reg_citations = reg_citations
  end

  # GET /notice_requirements/1
  # GET /notice_requirements/1.json
  def show
  end

  # GET /notice_requirements/new
  def new
    @notice_requirement = NoticeRequirement.new
  end

  # GET /notice_requirements/1/edit
  def edit
  end

  # POST /notice_requirements
  # POST /notice_requirements.json
  def create
    @notice_requirement = NoticeRequirement.new(notice_requirement_params)

    respond_to do |format|
      if @notice_requirement.save
        format.html { redirect_to @notice_requirement, notice: 'Notice requirement was successfully created.' }
        format.json { render :show, status: :created, location: @notice_requirement }
      else
        format.html { render :new }
        format.json { render json: @notice_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notice_requirements/1
  # PATCH/PUT /notice_requirements/1.json
  def update
    respond_to do |format|
      if @notice_requirement.update(notice_requirement_params)
        format.html { redirect_to @notice_requirement, notice: 'Notice requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice_requirement }
      else
        format.html { render :edit }
        format.json { render json: @notice_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notice_requirements/1
  # DELETE /notice_requirements/1.json
  def destroy
    @notice_requirement.destroy
    respond_to do |format|
      format.html { redirect_to notice_requirements_url, notice: 'Notice requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_notice_requirement
    @notice_requirement = NoticeRequirement.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_requirement_params
    params.fetch(:notice_requirement, {})
  end

  def act_citations
    modify_citation_list(NoticeRequirement.all.pluck(:act_cites))
  end

  def reg_citations
    modify_citation_list(NoticeRequirement.all.pluck(:regulation_cites))
  end

  def modify_citation_list(citations)
    citations.flatten
             .compact
             .map { |c| c.split(', ') }
             .flatten.uniq.sort
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notice_requirements_helper.rb
module NoticeRequirementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcpaNoticeRequirements</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notice_requirements/_form.html.erb
<%= form_with(model: notice_requirement, local: true) do |form| %>
  <% if notice_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice_requirement.errors.count, "error") %> prohibited this notice_requirement from being saved:</h2>

      <ul>
        <% notice_requirement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notice_requirements/edit.html.erb
<h1>Editing Notice Requirement</h1>

<%= render 'form', notice_requirement: @notice_requirement %>

<%= link_to 'Show', @notice_requirement %> |
<%= link_to 'Back', notice_requirements_path %>

app/views/notice_requirements/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row title-text">
      <div class="col-sm-12 align-self-end">
        <h1 class="display-4 highlight-text">CCPA NOTICE REQUIREMENTS</h1>
        <h3 class="display-6 highlight-text"></h3>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 d-flex align-items-stretch">
      <div class="card shadow-hover">
        <div class="card-body">
          <h1 class="card-title">CCPA Notice Requirements</h1>
          <h5 class="card-subtitle">Your guide to understanding the notices a business must provide before or at the time of personal information collection </h5>
        </div>
        <div class="card-body">
          <p class="card-text">This website is a project that was spawned from a charting assignment given by Professor Liisa Thomas at Northwestern Pritzker School of Law. It will be updated to include links to the actual citations as well as more of CCPA and eventually other privacy regulations.</p>
        </div>
        <div class="card-body">
          <p class="card-text">Use the filters to find the requirements that you need.</p>
        </div>
      </div>
    </div>

    <div class="col-sm-6 d-flex align-items-stretch">
      <div class="card shadow-hover">
        <div class="card-body">
          <h6 class="card-title">Filters</h6>
          <%= form_tag notice_requirements_path, method: 'get' do %>
            <%= label_tag :topic %>
            <%= select_tag :topic, options_for_select(NoticeRequirement::Topics.all, selected: params[:topic]), include_blank: 'All' %>
            <%= label_tag :act_citation, 'Act Citations' %>
            <%= select_tag :act_citation, options_for_select(@act_citations, selected: params[:act_citation]), include_blank: 'All' %>
            <%= label_tag :reg_citation, 'Regulation Citations' %>
            <%= select_tag :reg_citation, options_for_select(@reg_citations, selected: params[:reg_citation]), include_blank: 'All' %>
            <%= label_tag :text_search %>
            <%= text_field_tag :text_search, params[:text_search] %>
            <%= submit_tag "Apply" %>
            <%= link_to "Clear", notice_requirements_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <table class="table table-hover shadow-hover">
    <thead class="thead-dark">
      <tr>
        <th>Requirement</th>
        <th>Pin Cites from CCPA Act</th>
        <th>Pin Cites from CCPA Proposed Regulations</th>
<!--        <th colspan="3"></th>-->
      </tr>
    </thead>

    <tbody>
      <% current_topic = '' %>
      <% @notice_requirements.each do |notice_requirement| %>
        <% if notice_requirement.topic != current_topic %>
          <% current_topic = notice_requirement.topic %>
          <tr class="table-dark">
            <td colspan="7"><%= notice_requirement.topic.upcase %></td>
          </tr>
        <% end %>
        <tr>
          <td><%= notice_requirement.requirement %></td>
          <td><%= notice_requirement.act_cites %></td>
          <td><%= notice_requirement.regulation_cites %></td>
  <!--        <td><%#= link_to 'Show', notice_requirement %></td>-->
  <!--        <td><%#= link_to 'Edit', edit_notice_requirement_path(notice_requirement) %></td>-->
  <!--        <td><%#= link_to 'Destroy', notice_requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/notice_requirements/new.html.erb
<h1>New Notice Requirement</h1>

<%= render 'form', notice_requirement: @notice_requirement %>

<%= link_to 'Back', notice_requirements_path %>

app/views/notice_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_notice_requirement_path(@notice_requirement) %> |
<%= link_to 'Back', notice_requirements_path %>